### ISSUE TITLE
Soucis crusher immersive

### ISSUE THREAD

**Issue by madkoin** [Gogo08190/Chroma-Technology#2]
Bonjour,

je rencontre un soucis avec le crusher d'immersive, après avoir fini de l'assembler et de l'avoir relié en energie celui-ci je fonctionne pas.

Voici une petite video pour mieu comprendre.
https://youtu.be/TBTYTD6XpRU

**Comment by Gogo08190** [comment]
L’item que tu as mis ne peut pas se faire crusher je pense, vu que tu as reçu des dégâts la machine fonctionne. De plus moi de mon côté tout fonctionne bien.

**Comment by madkoin** [comment]
J'ai mis du coal coke de immersive, celui qui sert a faire du hop graphite, donc si l'item doit être accepté normalement.

**Comment by madkoin** [comment]
Je viens de regarder la console de log pendant que je met du coke dans le crusher, voici le résultat
Version 1.3.1
```

[13:32:34] [Server thread/FATAL] [FML]: ---- Minecraft Crash Report ----
--
// You should try our sister game, Minceraft!
 
Time: 2020-09-06 13:32:34 UTC
Description: Colliding entity with block
 
java.lang.ArithmeticException: / by zero
at  blusunrize.immersiveengineering.common.blocks.metal.TileEntityMultiblockMetal$MultiblockProcess.<init>(TileEntityMultiblockMetal.java:479)
at  blusunrize.immersiveengineering.common.blocks.metal.TileEntityMultiblockMetal$MultiblockProcessInWorld.<init>(TileEntityMultiblockMetal.java:807)
at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.onEntityCollision(TileEntityCrusher.java:321)
at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.onEntityCollision(BlockIETileProvider.java:734)
at net.minecraft.entity.Entity.doBlockCollisions(Entity.java:1044)
at net.minecraft.entity.Entity.move(Entity.java:964)
at net.minecraft.entity.item.EntityItem.TickCentral_TrueOnUpdateTick(EntityItem.java:122)
at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102)
at net.minecraft.entity.item.EntityItem.onUpdate(EntityItem.java)
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
at net.minecraft.world.World.updateEntity(World.java:1958)
at net.minecraft.world.World.redirect$zzp000$updateEntity(World.java:5123)
at net.minecraft.world.World.updateEntities(World.java:1762)
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Block being collided with --
Block:  immersiveengineering:metal_multiblock[_0multiblockslave=false,_1dynamicrender=false,boolean0=false,facing=north,type=crusher]
Block location: World: (1041,42,-9134), Chunk: (at 1,2,2 in 65,-571;  contains blocks 1040,0,-9136 to 1055,255,-9121), Region: (2,-18;  contains chunks 64,-576 to 95,-545, blocks 1024,0,-9216 to  1535,255,-8705)
 
-- Entity being checked for collision --
Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
Entity ID: 49406663
Entity Name: item.item.immersiveengineering.material.coal_coke
Entity's Exact location: 1041.94, 42.98, -9133.33
Entity's Block location: World: (1041,42,-9134), Chunk: (at 1,2,2 in  65,-571; contains blocks 1040,0,-9136 to 1055,255,-9121), Region:  (2,-18; contains chunks 64,-576 to 95,-545, blocks 1024,0,-9216 to  1535,255,-8705)
Entity's Momentum: -0.12, -0.50, -0.02
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Entity NBT:  {Motion:[-0.1240718741322254d,-0.49964595300737236d,-0.02485016587367583d],ForgeData:{thrower:"MadKoin"},UUIDLeast:-6099198641792252394L,Health:5s,RelativeAABB:[-0.125d,0.0d,-0.125d,0.125d,0.25d,0.125d],Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[25.621082f,0.0f],Thrower:"MadKoin",UpdateBlocked:0b,FallDistance:3.5408518f,Item:{id:"immersiveengineering:material",Count:1b,Damage:6s},UUIDMost:7177891412639501369L,Pos:[1041.9389098448019d,42.97914824838432d,-9133.32908759133d],PickupDelay:30s,Fire:-1s,ForgeCaps:{"enderutilities:entity_portal_cooldown":{LastInPortal:0L},"pneumaticcraft:hacking":{}},Lifespan:6000,Age:9s}
 
-- Entity being ticked --
Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
Entity ID: 49406663
Entity Name: item.item.immersiveengineering.material.coal_coke
Entity's Exact location: 1041.94, 42.98, -9133.33
Entity's Block location: World: (1041,42,-9134), Chunk: (at 1,2,2 in  65,-571; contains blocks 1040,0,-9136 to 1055,255,-9121), Region:  (2,-18; contains chunks 64,-576 to 95,-545, blocks 1024,0,-9216 to  1535,255,-8705)
Entity's Momentum: -0.12, -0.50, -0.02
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Entity NBT:  {Motion:[-0.1240718741322254d,-0.49964595300737236d,-0.02485016587367583d],ForgeData:{thrower:"MadKoin"},UUIDLeast:-6099198641792252394L,Health:5s,RelativeAABB:[-0.125d,0.0d,-0.125d,0.125d,0.25d,0.125d],Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[25.621082f,0.0f],Thrower:"MadKoin",UpdateBlocked:0b,FallDistance:3.5408518f,Item:{id:"immersiveengineering:material",Count:1b,Damage:6s},UUIDMost:7177891412639501369L,Pos:[1041.9389098448019d,42.97914824838432d,-9133.32908759133d],PickupDelay:30s,Fire:-1s,ForgeCaps:{"enderutilities:entity_portal_cooldown":{LastInPortal:0L},"pneumaticcraft:hacking":{}},Lifespan:6000,Age:9s}

```
Je n'ai pas mis la suite (System Details) avec la liste de tout les mods et leur version, si tu en a besoin je les rajouterais.

Cela génère un rapport de crash, mais sans faire crash le serveur
